# Generated by Django 4.2.3 on 2023-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_alter_friendlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
