# Generated by Django 4.2.3 on 2023-07-30 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_profilepicture_image_alter_userinfo_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01', null=True),
        ),
        migrations.CreateModel(
            name='UserMobileOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('mobile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info_mobile_otp', to='useraccount.userinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_mobile_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
